In [70]:
import numpy as np

# Q1

In [71]:
B = np.matrix([[1, 2,-3], [3, 4,-1]])
A = np.matrix([[2,5,-1] , [1 ,4 ,5], [2 ,-1 ,6]])
y =           [2, -4, 1]
z =           [-15, -8, -22]

In [72]:
np.matmul(B, A)

matrix([[-2, 16, -9],
        [ 8, 32, 11]])

In [73]:
np.matmul(A ,B.transpose())

matrix([[ 15,  27],
        [ -6,  14],
        [-18,  -4]])

In [74]:
np.matmul(A,y)

matrix([[-17,  -9,  14]])

In [75]:
np.dot(y,z)

-20

# Q2

In [100]:
#rows
def print_rows(B):
    for i in B:
        print(i)
        
print_rows(B)

[[ 1  2 -3]]
[[ 3  4 -1]]


In [101]:
B.shape

(2, 3)

In [102]:
#columns
def print_cols(B):
    for i in range((B.shape[1])):
        print(B[:,i])

print_cols(B)

[[1]
 [3]]
[[2]
 [4]]
[[-3]
 [-1]]


# Q3

In [79]:
foo = np.arange(0,30)

In [80]:
foo.shape

(30,)

In [81]:
bar = foo.reshape((15,2))

In [82]:
bar

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [83]:
bar[1][0] = -1

In [84]:
foo

array([ 0,  1, -1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [103]:
# Total sum
sum(sum(bar))

432

In [104]:
# Columns sum
sum(bar)

array([207, 225])

In [105]:
# Rows sum
for i in bar:
    print(sum(i))

1
2
9
13
17
21
25
29
33
37
41
45
49
53
57


# Q4

In [151]:
intMat = np.arange(0,100).reshape((10,10))

In [152]:
intMat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [153]:
permIntMat = np.random.shuffle(intMat)

In [154]:
intMat

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [155]:
vec = np.random.randint(low=1, high=100, size=10)

In [156]:
vec

array([26, 67, 52, 67, 79, 18, 56, 52,  7, 27])

In [157]:
all = np.vstack([intMat,vec])

In [158]:
all

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [26, 67, 52, 67, 79, 18, 56, 52,  7, 27]])

# Q5

In [163]:
def min_max_scaling(all):

    for col in range(all.shape[1]):

        currentColumn = all[:,col]
        mini = currentColumn.min()
        maxi = currentColumn.max()

        print('\n column:',currentColumn,' min:',mini,' max:',maxi,'\n')

        for rowidx,cell in enumerate(currentColumn):

            newValue = (cell-mini)/(maxi-mini)
            newValue = round(newValue,3)

            print("index:" ,rowidx,col,'\t  Value:',cell,'new',newValue)

            all[rowidx,col] = newValue

In [164]:
print("\n The Scaling matrix is:\n")
min_max_scaling(all)


 The Scaling matrix is:


 column: [50 70 80 60 30 40 10 90 20  0 26]  min: 0  max: 90 

index: 0 0 	  Value: 50 new 0.556
index: 1 0 	  Value: 70 new 0.778
index: 2 0 	  Value: 80 new 0.889
index: 3 0 	  Value: 60 new 0.667
index: 4 0 	  Value: 30 new 0.333
index: 5 0 	  Value: 40 new 0.444
index: 6 0 	  Value: 10 new 0.111
index: 7 0 	  Value: 90 new 1.0
index: 8 0 	  Value: 20 new 0.222
index: 9 0 	  Value: 0 new 0.0
index: 10 0 	  Value: 26 new 0.289

 column: [51 71 81 61 31 41 11 91 21  1 67]  min: 1  max: 91 

index: 0 1 	  Value: 51 new 0.556
index: 1 1 	  Value: 71 new 0.778
index: 2 1 	  Value: 81 new 0.889
index: 3 1 	  Value: 61 new 0.667
index: 4 1 	  Value: 31 new 0.333
index: 5 1 	  Value: 41 new 0.444
index: 6 1 	  Value: 11 new 0.111
index: 7 1 	  Value: 91 new 1.0
index: 8 1 	  Value: 21 new 0.222
index: 9 1 	  Value: 1 new 0.0
index: 10 1 	  Value: 67 new 0.733

 column: [52 72 82 62 32 42 12 92 22  2 52]  min: 2  max: 92 

index: 0 2 	  Value: 52 new 0.556
index: 1